run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mattermost/matterbuild
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
