{{- if .Values.configuration_extra }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "matterbuild.fullname" . }}-envvars
  labels:
    {{- include "matterbuild.labels" . | nindent 4 }}
data:
  CA_CERT: {{ .Values.configuration_extra.CA_CERT | quote }}
  SSL_VERIFY: {{ .Values.configuration_extra.SSL_VERIFY | quote }}
{{- end }}

---
{{- if .Values.configuration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "matterbuild.fullname" . }}-config
  labels:
    {{- include "matterbuild.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Values.configuration | toJson }}
{{- end }}
