---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: matterbuild

configMapGenerator:
  - name: matterbuild
    literals:
      - SSL_VERIFY="false"
      - CA_CERT="false"
